---
title: "rOpenSci Champions Program. Mentorship Training and Orientation"
---

This course is part of the rOpenSci Champion Program's mentor training and orientation. 

Mentors play a vital role in the rOpenSci Champions Program by helping select the first cohort of Champions and advising and inspiring their mentees. Mentors will also __connect__ their mentees to people, programs, and organizations; __recommend__, resources, readings, training, and experiences; and provide __feedback__ on the mentee’s project.

After this trainig, mentors will work with Champions to develop their project, which can be one of the following options:

* Create a new package;
* Go through the review process with an R package they have already developed;
* Serve as a reviewer for the rOpenSci software peer review system.

Mentors may also support Champions with delivering other activities including: giving a talk, writing blog posts, and teaching other community 

## Who our mentors are?

All training is designed with some learner personas in mind. As a community, we also have personas to describe our members.  When we build this training material, we think about this persona:

Fausti

:   sent their packages to [rOpenSci review process](https://ropensci.org/software-review/) a couple of years ago. The process ensured the quality of their software and facilitated its publication in [JOSS](https://joss.theoj.org/), which gave them academic credit. Also, getting the rOpenSci badge as an international organization helped other colleagues take their software products more seriously and as valid research products.
Fausti volunteered to review packages in Spanish, and advised other colleagues to send their packages to review because their experience was very good.
Fausti learned about the [champions program](https://ropensci.org/champions/) and volunteered to mentor because they can give back to the community. It is also, a way to be trained as a mentor, which is a good skill for their academic role and to increase their contact network.


During this training and orientation, Fausti will gain mentoring skills (active listening, effective questioning, giving feedback), will receive resources for their mentoring role such as the Mentors Guidelines, Meeting Templates and details of the logistics of the champions program.


## Sources

We use different sources to build this training and the material. We thank these organizations and their authors for sharing their material under an open license that we can reuse and remix.

* [Mozilla Open Leaders](https://foundation.mozilla.org/en/initiatives/mozilla-open-leaders/) 
* [Teaching Tech Together](https://teachtogether.tech/en/index.html) 
* [The Carpentries Instructor Training](https://carpentries.github.io/instructor-training/) 

## How to use this material

If you want to use this material for teaching you can find Instructor notes with a scripts for the course, extra content for the slides and an explanation of the exercises.

In the material section, you can access the slides and other templates documents that you can copy, resuse and remix for your training. 

### License

This work is licensed under the [Creative Commons Attribution-NonCommercial 4.0](https://creativecommons.org/licenses/by-nc/4.0/) license (CC-BY-NC-4.0).

### How to cite this work

Bellini Saibene, Yanina. rOpenSci Champions Program. Mentorship Training and Orientation. (2023).
