on:
  push:
    branches:
      main
  schedule:
    - cron:  '0 12 * * *'

name: Render-Book

jobs:
  babelquarto:
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    name: Render-Book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::.

      - name: Render book
        run: Rscript -e 'babelquarto::render_book()'

      - name: git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-pages committer"

      - name: Commit results
        env: # Set the secret as an input
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          cd docs
          git init
          git add .
          git commit -m 'update site'
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:gh-pages --force